export const typeColors = [
  { name: "normal", colorName: "teal" },
  { name: "fire", colorName: "red" },
  { name: "water", colorName: "blue" },
  { name: "electric", colorName: "yellow" },
  { name: "grass", colorName: "green" },
  { name: "ice", colorName: "teal" },
  { name: "fighting", colorName: "orange" },
  { name: "poison", colorName: "purple" },
  { name: "ground", colorName: "cyan" },
  { name: "flying", colorName: "cyan" },
  { name: "psychic", colorName: "pink" },
  { name: "bug", colorName: "green" },
  { name: "rock", colorName: "brown" },
  { name: "ghost", colorName: "purple" },
  { name: "dragon", colorName: "purple" },
  { name: "dark", colorName: "black" },
  { name: "steel", colorName: "gray" },
  { name: "fairy", colorName: "pink" },
];
